# Fubon Neo Trading Credentials
ACCOUNT = "YOUR_ACCOUNT"
PASSWORD = "YOUR_PASSWORD"
CERT_PATH = r"C:\PATH\TO\YOUR\CERTIFICATE.pfx"  # Use raw string for Windows path
CERT_PASSWORD = "YOUR_CERTIFICATE_PASSWORD"